### ISSUE TITLE
create a document with a list of basic bash commands

### ISSUE THREAD

**Issue by KristijanArmeni** [Donders-Institute/git-workshop#24]
## Summary
This issue links to #23 (check who's working on these)

When working with git it is convenient to work on the command line. Therefore, it is helpful to know how to navigate through directories through command line tools.  Let's create a document called `bash_commands.md` in which will collect some of the most common bash commands. For now, just create the file with a title.

## How to go about this issue:
- make sure you pull the most recent changes from the origin (i.e. that it is up to date)
- make sure you push your local repository to your fork (`git push <your_fork_name> master`)
- create a new markdown file in `/tutorial`
- add a descriptive title
- `git add` and `git commit` your changes and `git push` to your fork. Don't forget to reference this issue in your commit simply type # and the issue number in your commit message!
- make sure you assign someone to review the pull request (PR) for this issue

**Comment by robertoostenveld** [comment]
I have added a Bash document with https://github.com/Donders-Institute/git-workshop/commit/5e23d3649e8b12e46134e71830c4672a058c9785 that closes #24, #25, #26, #27.
