### ISSUE TITLE
create a document with a list of basic git commands

### ISSUE THREAD

**Issue by KristijanArmeni** [Donders-Institute/git-workshop#28]
## Summary
While you can get quite far with the basic git commands `git add`, `git commit` etc. many of them are much more versatile than you might expect. For example every git command comes with several optional flags which slightly change the behavior of the command. 

How about we create a document in which we collect the most common git commands with some of their optional behavior. For this you will first create a new document (`git_commands.md`) within the `/tutorial` subfolder for your collaborators to fill with content. For now, only add a meaninful title in the doc.

## How to go about this issue:
- make sure you pull the most recent changes from the origin (i.e. that it is up to date)
- make sure you push your local repository to your fork (`git push <your_fork_name> master`), i.e. that your fork is in sync with the origin
- create the markdown file `git_commands.md`
- add a descriptive title 
- `git add` and `git commit` your changes and `git push` to your fork. Don't forget to reference this issue in your commit simply type # and the issue number in your commit message!
- make sure you assign someone to review the pull request (PR) for this issue

**Comment by robertoostenveld** [comment]
I think this is sufficiently addressed with https://github.com/Donders-Institute/git-workshop/blob/master/materials/git_resources.md, as well as #29 and #30.
