### ISSUE TITLE
Not enough references to cats in Kristin's presentation page

### ISSUE THREAD

**Issue by pietrotrope** [Donders-Institute/git-workshop#71]
Hi, there is a problem in Kristin's md file. 
To be more precise, there are no references to cats.

Please add a reference to cats

**Comment by KristinKalt** [comment]
Thanks for that comment, done! :D @pietrotrope

**Comment by KristinKalt** [comment]
@LaerkeHoegenhaven , like my cat on my md page? :)

**Comment by pietrotrope** [comment]
Yes, Nice cat :)
I'll close the issue
