### ISSUE TITLE
Fix group 4 ReadMe

### ISSUE THREAD

**Issue by melanieganz** [Donders-Institute/git-workshop#73]
Can you please fix group 4 ReadMe @pietrotrope?

**Comment by melanieganz** [comment]
and @VadymV maybe you can help too?

**Comment by melanieganz** [comment]
can you both also add a new movie, I can only come up with 3...

**Comment by melanieganz** [comment]
are you done? what is happening? ;-)

**Comment by pietrotrope** [comment]
> Can you please fix group 4 ReadMe @pietrotrope?

Fixed! Forgot to close the issue.
