### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by Pneumaethylamine** [Donders-Institute/git-workshop#81]
This is confusing

**Comment by Pneumaethylamine** [comment]
But it is getting less confusing

**Comment by Pneumaethylamine** [comment]
My bad wrong place wrong issue

**Comment by robertoostenveld** [comment]
Interesting ... all of a sudden I am getting activity on this repository. 

@Pneumaethylamine are you running or participating in a git/github training or so? And are you (re)using this material?

**Comment by robertoostenveld** [comment]
Or is @CPernet perhaps using this (or a copy of this) repository in a training?

**Comment by CPernet** [comment]
Indeed lol
